Repository team-coderder/Backend, pull requests merged in 2022-10, with the labels that each got.

#12 #5 merge : PostgreSQL 연결 완료
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#13 #11 merge : modeling 완료
  .gitignore
  build.gradle
  src/main/java/com/coderder/colorMeeting/ColorMeetingApplication.java
  src/main/java/com/coderder/colorMeeting/model/Group.java
  src/main/java/com/coderder/colorMeeting/model/GroupMember.java
  src/main/java/com/coderder/colorMeeting/model/GroupMemberId.java
  src/main/java/com/coderder/colorMeeting/model/Member.java
  src/test/java/com/coderder/colorMeeting/MemberRepositoryTest.java
Labels: enhancement

#16 #15 fix : Github Actions - properties 생성 코드 수정
  .github/workflows/deploy.yml
Labels: bug

#33 Feature #31 team domain
  src/main/java/com/coderder/colorMeeting/controller/TeamController.java
  src/main/java/com/coderder/colorMeeting/dto/request/TeamMemberRequestDto.java
  src/main/java/com/coderder/colorMeeting/dto/request/TeamRequestDto.java
  src/main/java/com/coderder/colorMeeting/dto/response/TeamMemberDto.java
  src/main/java/com/coderder/colorMeeting/dto/response/TeamMembersResponseDto.java
  src/main/java/com/coderder/colorMeeting/dto/response/TeamResponseDto.java
  src/main/java/com/coderder/colorMeeting/exception/ErrorCode.java
  src/main/java/com/coderder/colorMeeting/exception/GlobalExceptionHandler.java
  src/main/java/com/coderder/colorMeeting/exception/TeamMemberNotFoundException.java
  src/main/java/com/coderder/colorMeeting/exception/TeamNotFoundException.java
  src/main/java/com/coderder/colorMeeting/model/Member.java
  src/main/java/com/coderder/colorMeeting/model/Team.java
  src/main/java/com/coderder/colorMeeting/model/TeamMember.java
  src/main/java/com/coderder/colorMeeting/repository/GroupMemberRepository.java
  src/main/java/com/coderder/colorMeeting/repository/TeamMemberRepository.java
  src/main/java/com/coderder/colorMeeting/repository/TeamRepository.java
  src/main/java/com/coderder/colorMeeting/service/GroupService.java
  src/main/java/com/coderder/colorMeeting/service/TeamService.java
  src/main/resources/application.properties
Labels: enhancement

#35 Feature #31 team domain
  src/main/java/com/coderder/colorMeeting/controller/TeamController.java
  src/main/java/com/coderder/colorMeeting/dto/response/ResponseMessage.java
  src/main/java/com/coderder/colorMeeting/exception/BadRequestException.java
  src/main/java/com/coderder/colorMeeting/exception/GlobalExceptionHandler.java
  src/main/java/com/coderder/colorMeeting/exception/InvalidGroupNameException.java
  src/main/java/com/coderder/colorMeeting/exception/MemberNotFoundException.java
  src/main/java/com/coderder/colorMeeting/exception/NotAuthorizedException.java
  src/main/java/com/coderder/colorMeeting/exception/NotFoundException.java
  src/main/java/com/coderder/colorMeeting/exception/TeamMemberNotFoundException.java
  src/main/java/com/coderder/colorMeeting/exception/TeamNotFoundException.java
  src/main/java/com/coderder/colorMeeting/exception/UnAuthorizedException.java
  src/main/java/com/coderder/colorMeeting/service/TeamService.java
Labels: enhancement, feedback wanted
